### ISSUE TITLE
Signature to pass to contract

### ISSUE THREAD

**Issue by HadarKeidar** [PROPSProject/props-token-distribution#2]
Hi.
The solution you suggesting is really nice but i can't understand the one thing, the signature needed is sig.length = 65 and i can't find out how to generate the signature using Web3.
when i use web3.eth.sign() i get sig.length = 134 and I'm not sure what the parameters i need to pass to the sign() function.

Can you explain how to generate the signature?
Thanks.

**Comment by lgalabru** [comment]
hi @HadarKeidar.

Maybe the tests can help you understand how to create the signature: https://github.com/PROPSProject/props-token-distribution/blob/a1a7488581e74e9c66b44a19edd7ff7caa792109/test/PropsToken.js#L87
Does it help?
Best

**Comment by HadarKeidar** [comment]
Yes it helped.
Thank you.
